version: 2
jobs:
    build:
        docker:
            - image: circleci/node:7
        steps:
            - checkout
            - run:
                name: install-dependencies
                command: npm install
            - run:
                name: eslint
                command: npm run eslint                
            - run:
                name: tests
                command: npm test
            - run:
                name: start
                command: npm start             